# Generated by Django 3.1.2 on 2020-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_randoms', models.IntegerField(default=None, null=True)),
                ('number_of_alternates', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
