# Generated by Django 3.1.3 on 2020-11-30 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_randoms', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_alternates', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RandomPuller.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PulledRandoms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_pulled', models.DateTimeField(auto_now_add=True)),
                ('pulled_alternates', models.ManyToManyField(related_name='pulled_alternates_list', to='RandomPuller.Employee')),
                ('pulled_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RandomPuller.company')),
                ('pulled_randoms', models.ManyToManyField(related_name='pulled_randoms_list', to='RandomPuller.Employee')),
            ],
            options={
                'verbose_name': 'Pulled Random List',
                'verbose_name_plural': 'Pulled Random Lists',
                'ordering': ['pulled_company', 'date_pulled'],
            },
        ),
    ]
