# Generated by Django 3.1.2 on 2020-11-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name')},
        ),
    ]
