# Generated by Django 3.1.2 on 2020-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_alternates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_randoms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
