# Generated by Django 3.1.2 on 2020-11-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0002_auto_20201106_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'company')},
        ),
    ]
