# Generated by Django 3.1.2 on 2020-11-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0003_auto_20201110_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
    ]
