# Generated by Django 3.1.2 on 2020-11-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0004_auto_20201110_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
