# Generated by Django 3.1.2 on 2020-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0006_auto_20201113_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_alternates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_randoms',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
