# Generated by Django 3.1.2 on 2020-11-13 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0007_auto_20201113_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulledRandoms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_pulled', models.DateTimeField(auto_now_add=True)),
                ('pulled_alternates', models.ManyToManyField(related_name='pulled_alternates_list', to='RandomPuller.Employee')),
                ('pulled_randoms', models.ManyToManyField(related_name='pulled_randoms_list', to='RandomPuller.Employee')),
            ],
        ),
    ]
