# Generated by Django 3.1.2 on 2020-11-20 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RandomPuller', '0008_pulledrandoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulledrandoms',
            name='pulled_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RandomPuller.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_alternates',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_randoms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
