# Generated by Django 3.1.3 on 2020-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberConsortiumPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_cost_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Member Consortium Pricing',
                'verbose_name_plural': 'Member Consortium Pricing',
            },
        ),
        migrations.CreateModel(
            name='NonMemberConsortiumPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_cost_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Non Member Consortium Pricing',
                'verbose_name_plural': 'Non Member Consortium Pricing',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyProgramSupportFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('charge_rate', models.CharField(max_length=200)),
                ('driver_num', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Third Party Program Support Fees',
                'verbose_name_plural': 'Third Party Program Support Fees',
            },
        ),
    ]
