# Generated by Django 3.1.2 on 2020-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberConsortiumPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third_party_billing_time', models.CharField(max_length=200)),
                ('third_party_driver_number', models.CharField(max_length=200)),
                ('third_party_fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Member Consortium Pricing',
                'verbose_name_plural': 'Member Consortium Pricing',
            },
        ),
        migrations.CreateModel(
            name='NonMemberConsortiumPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('non_member_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Non Member Consortium Pricing',
                'verbose_name_plural': 'Non Member Consortium Pricing',
            },
        ),
        migrations.DeleteModel(
            name='ConsortiumPricing',
        ),
    ]
