# Generated by Django 3.1.2 on 2020-11-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_auto_20201102_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonmemberconsortiumpricing',
            old_name='non_member_price',
            new_name='price',
        ),
    ]
