# Generated by Django 3.1.2 on 2020-11-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_auto_20201106_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyProgramSupportFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('charge_rate', models.CharField(max_length=200)),
                ('driver_num', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Third Party Program Support Fees',
                'verbose_name_plural': 'Third Party Program Support Fees',
            },
        ),
    ]
