# Generated by Django 3.1.2 on 2020-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_thirdpartyprogramsupportfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberconsortiumpricing',
            name='extra_cost_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nonmemberconsortiumpricing',
            name='extra_cost_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
