# Generated by Django 3.1.2 on 2020-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_auto_20201102_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmemberconsortiumpricing',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
