# Generated by Django 3.1.2 on 2020-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20201102_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberconsortiumpricing',
            name='third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberconsortiumpricing',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='memberconsortiumpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nonmemberconsortiumpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
