# Generated by Django 3.1.2 on 2020-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_auto_20201102_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberconsortiumpricing',
            name='third_party_billing_time',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='memberconsortiumpricing',
            name='third_party_driver_number',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='memberconsortiumpricing',
            name='third_party_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
