# Generated by Django 3.1.2 on 2020-11-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0006_auto_20201102_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberconsortiumpricing',
            name='third_party',
        ),
        migrations.RemoveField(
            model_name='memberconsortiumpricing',
            name='third_party_billing_time',
        ),
        migrations.RemoveField(
            model_name='memberconsortiumpricing',
            name='third_party_driver_number',
        ),
        migrations.RemoveField(
            model_name='memberconsortiumpricing',
            name='third_party_fee',
        ),
    ]
