# Generated by Django 3.1.2 on 2020-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0007_auto_20201102_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberconsortiumpricing',
            old_name='price',
            new_name='min_price',
        ),
        migrations.AddField(
            model_name='memberconsortiumpricing',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
