name: Coverage.py Report

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install coverage
        pip install -r requirements.txt
    - name: Run Coverage Tests
      run: |
        coverage run manage.py test
    - name: Get Coverage
      run: |
        coverage json
        content=`cat ./coverage.json`
        echo "::set-output name=coverageJson::$content"
    - run: |
        echo "${{ fromJson(stepls.set_var.outputs.coverageJson).totals.percent_covered }}"

#    - name: Upload coverage.json Artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: Coverage
#        path: coverage.json